# Generated by Django 4.1.7 on 2023-09-14 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileNumber', models.CharField(max_length=4, unique=True)),
                ('fullname', models.TextField()),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contact', models.BigIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('religion', models.CharField(max_length=15)),
                ('marital', models.CharField(max_length=15)),
                ('occupation', models.TextField(blank=True, null=True)),
                ('bloodPressure', models.CharField(max_length=15)),
                ('temperature', models.FloatField()),
                ('heartRate', models.CharField(max_length=5)),
                ('weight', models.FloatField()),
                ('saturation', models.FloatField()),
                ('lastVisit', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
