# Generated by Django 4.1.7 on 2023-09-15 07:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0002_alter_patient_bloodpressure_alter_patient_heartrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodPressure',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='heartRate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='marital',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
