# Generated by Django 4.1.7 on 2023-09-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_alter_patient_bloodpressure_alter_patient_heartrate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='bloodPressure',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
