# Generated by Django 4.1.7 on 2023-09-15 07:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_alter_patient_occupation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 7, 58, 44, 769547, tzinfo=datetime.timezone.utc)),
        ),
    ]
