# Generated by Django 4.1.7 on 2023-09-15 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_alter_patient_lastvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 15, 8, 35, 39, 321115, tzinfo=datetime.timezone.utc)),
        ),
    ]
