# Generated by Django 4.1.7 on 2023-09-15 08:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0008_alter_patient_lastvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
