# Generated by Django 4.1.7 on 2023-09-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0009_alter_patient_lastvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='regDate',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
