# Generated by Django 4.1.7 on 2023-09-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_id',
            field=models.BigIntegerField(),
        ),
    ]
