# Generated by Django 4.1.7 on 2023-09-18 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_alter_customuser_user_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
