# Generated by Django 4.1.7 on 2024-01-13 21:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(default=None, max_length=10, null=True)),
                ('blocked', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(default=None, null=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('password_changed', models.BooleanField(default=False)),
                ('description', models.TextField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('gender', models.CharField(default='M', max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField(default=None, null=True)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dept_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('formulation', models.CharField(default=None, max_length=100, null=True)),
                ('qty', models.PositiveIntegerField(default=None, null=True)),
                ('describe', models.TextField(default=None, null=True)),
                ('addDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('expiryDate', models.DateField(default=None, null=True)),
                ('lastEdited', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('hidden', models.BooleanField(default=False)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.department')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ICD10_codes',
            fields=[
                ('id', models.AutoField(primary_key=True)),
                ('code', models.CharField(max_length=15)),
                ('describe', models.TextField()),
                ('deleted', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fileNumber', models.CharField(max_length=8, unique=True)),
                ('fullname', models.CharField(max_length=255)),
                ('birthDate', models.DateField()),
                ('gender', models.CharField(max_length=6)),
                ('address', models.TextField()),
                ('contact', models.CharField(default=None, max_length=10, null=True)),
                ('comment', models.TextField(default=None, null=True)),
                ('religion', models.CharField(default=None, max_length=15, null=True)),
                ('marital', models.CharField(default=None, max_length=30, null=True)),
                ('occupation', models.CharField(default=None, max_length=150, null=True)),
                ('regDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('lastVisit', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted', models.BooleanField(default=False)),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doctor_service', models.BooleanField(default=False, null=True)),
                ('costEach', models.FloatField()),
                ('pay_status', models.CharField(default='cash', max_length=12)),
                ('comp_status', models.CharField(default='waiting', max_length=50)),
                ('md_qty', models.PositiveIntegerField(default=None, null=True)),
                ('md_formulation', models.CharField(default=None, max_length=100, null=True)),
                ('md_dosage', models.TextField(default=None, null=True)),
                ('doctor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='doctor_services', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.patient')),
                ('registrar', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='dbase.dept_service')),
            ],
        ),
        migrations.CreateModel(
            name='Tool_requests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('serve_date', models.DateTimeField(default=None, null=True)),
                ('qty', models.PositiveIntegerField(default=None, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('describe', models.TextField(default=None, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.dept_service')),
            ],
        ),
        migrations.CreateModel(
            name='Test_results',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('result_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('seen_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('micro', models.TextField(default=None, null=True)),
                ('macro', models.TextField(default=None, null=True)),
                ('report', models.TextField(default=None, null=True)),
                ('rows', models.JSONField(default=None, null=True)),
                ('new_tests', models.JSONField(default=None, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.patient')),
                ('patient_test', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.patient_service')),
            ],
        ),
        migrations.CreateModel(
            name='Patient_vitals',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bloodPressure', models.CharField(max_length=15)),
                ('temperature', models.FloatField()),
                ('heartRate', models.FloatField()),
                ('weight', models.FloatField()),
                ('saturation', models.FloatField()),
                ('add_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.patient')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient_credit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('credit_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount', models.FloatField()),
                ('use_date', models.DateTimeField(default=None, null=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='dbase.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('diagnosis_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_chief', models.TextField(default=None, null=True)),
                ('d_assess', models.TextField(default=None, null=True)),
                ('rev_systems', models.JSONField(default=None, null=True)),
                ('pat_history', models.JSONField(default=None, null=True)),
                ('fam_history', models.JSONField(default=None, null=True)),
                ('physical_exam', models.JSONField(default=None, null=True)),
                ('icd_codes', models.JSONField(default=None, null=True)),
                ('tests', models.JSONField(default=None, null=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.patient')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dbase.department'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.group'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='custom_users', to='auth.permission'),
        ),
    ]
