# Generated by Django 4.1.7 on 2024-02-12 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0003_alter_icd10_codes_describe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 9, 42, 43, 599886, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 12, 9, 42, 43, 599886, tzinfo=datetime.timezone.utc)),
        ),
    ]
