# Generated by Django 4.1.7 on 2024-02-17 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0007_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 206637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dept_service',
            name='addDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 225104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='dept_service',
            name='lastEdited',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 225104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 228102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 226104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regDate',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 226104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient_credit',
            name='credit_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 229102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient_service',
            name='service_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 227103, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='patient_vitals',
            name='add_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 226104, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='result_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 228102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='seen_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 228102, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tool_requests',
            name='request_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 17, 5, 14, 11, 230102, tzinfo=datetime.timezone.utc)),
        ),
    ]
