# Generated by Django 4.1.7 on 2024-02-17 10:44

import apps.dbase.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbase', '0012_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='dept_service',
            name='addDate',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='dept_service',
            name='lastEdited',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='diagnosis',
            name='diagnosis_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='patient',
            name='lastVisit',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='patient',
            name='regDate',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='patient_credit',
            name='credit_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='patient_service',
            name='service_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='patient_vitals',
            name='add_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='result_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='test_results',
            name='seen_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
        migrations.AlterField(
            model_name='tool_requests',
            name='request_date',
            field=models.DateTimeField(default=apps.dbase.models.def_datetime),
        ),
    ]
